### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by AlexisHutin** [terdia/mqttui#1]
hello,
First thanks for your work :)

I'd like to use your sofware and install it through portainer.
So I tried to make a docker-compose file for portainer like this : 

```
version: '3'
services:
  mqttui:
    image: terdia07/mqttui:latest
    container_name: mqttui
    restart: unless-stopped
    ports:
      - "5858:5000"
    volumes:
      - /my/nice/path:/app
    env_file:
      - stack.env
```

The image is downloaded correctly but the app start with this error : 
```
Usage: flask run [OPTIONS]

Try 'flask run --help' for help.

Error: Could not import 'app'.

 * Serving Flask app 'app.py' (lazy loading)

 * Environment: production

   WARNING: This is a development server. Do not use it in a production deployment.

   Use a production WSGI server instead.

 * Debug mode: off
```

Do you know how can I fix this ?

Thx :)

**Comment by terdia** [comment]
The problem likely stems from conflicting configurations between your Docker Compose file and the image's built-in settings. Here's how to resolve it:

```
version: '3'
services:
  mqttui:
    image: terdia07/mqttui:latest
    container_name: mqttui
    restart: unless-stopped
    ports:
      - "5858:5000"
    env_file:
      - stack.env
```

Any reason why you are mounting a volume? 
```
    volumes:
      - /my/nice/path:/app
```
      
If you need to customize the application, consider building a new image based on `terdia07/mqttui` rather than using volume mounts or overriding commands.

If the issue persists after these changes, please provide the full container logs for further troubleshooting.
